### ISSUE TITLE
view folder

### ISSUE THREAD

**Issue by Alex470** [WHW-HD/frog-web#5]
Ich möchte gerne in views/index.mustache Teile thematisch auslagern. 
Ich werde noch ein Unterverzeichnis anlegen

--view/partials

**Comment by Alex470** [comment]
Ich möchte gerne auch noch ein eigenes css für index.mustache einführen.

**Comment by felixgonschorek** [comment]
kein veto von mir, gute idee :+1:

**Comment by Alex470** [comment]
Es gibt einen issue#5 Branch. 
Der enthält die besprochenen Änderungen in /views und das Stylesheet. 

Dann ist noch eine super simple Navigation mit Pagelinks enthalten. Das ist nur zum Test. 

Was in den nächsten Schritten gemacht wird/werden soll, wollte Felix noch festlegen.

**Comment by felixgonschorek** [comment]
sieht gut aus!

http://195.201.28.189:3000
